=== nkutsche/xmlml/samples/demo_schematron/asterix.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT asterix-universe (group+) >

<!ELEMENT group (name, character+) >

<!ELEMENT name (#PCDATA) >

<!ELEMENT position (#PCDATA) >

<!ELEMENT character (name, position) >

<!ATTLIST group xml:id ID #IMPLIED >
<!ATTLIST character xml:id ID #IMPLIED  
                    species CDATA "human">

<!ENTITY r "®" >
<!ENTITY oe "ö" >
<!ENTITY ae "ä" >

=== nkutsche/xmlml/samples/demo_schematron/asterix-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE asterix-universe SYSTEM "asterix.dtd">
<?xml-model href="demo.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<asterix-universe>
    <group xml:id="galier">
        <name>Galier</name>
        <character xml:id="ast">
            <name>Asterix&r;</name>
            <position>Warrior</position>
        </character>
        <character 
            xml:id="obel" 
            species="human"
            >
            <name>Obelix&r;</name>
            <position>Menhir supplier</position>
        </character>
        <character xml:id="idf" species="dog">
            <name>Idefix&r;</name>
            <position>Dog of Obelix</position>
        </character>
        <character xml:id="maj">
            <name>Majestix</name>
            <position>Chief</position>
        </character>
    </group>
    <group xml:id="roman">
        <name>R&oe;mer</name>
        <character xml:id="cÃ¤s">
            <name>C&#xe4;sar</name>
            <position>Imperator</position>
        </character>
        <character xml:id="gabo">
            <name>Gaius Bonus</name>
            <position>Centurion</position>
        </character>
    </group>
</asterix-universe>
